alg_name: "FT"
model_name: "meta-llama/Meta-Llama-Guard-2-8B"
device: 0

layers: [28]
num_steps: 20
batch_size: 4
max_length: 1024
lr: 5e-3
weight_decay: 0
kl_factor: 0
norm_constraint: false

objective_optimization: "target_new"
rewrite_module_tmp: "model.layers.{}.mlp"
layer_module_tmp: "model.layers.{}"
mlp_module_tmp: "model.layers.{}.mlp"
attn_module_tmp: "model.layers.{}.self_attn"
ln_f_module: "model.norm"
lm_head_module: "lm_head"
model_parallel: false
